import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// PlantIdentifierCare — generated by AppFactoryKit appgen from niche "plant-id".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum PlantIdentifierCareFactory {
    static func make() -> AppFactory {
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "PlantIdentifierCare",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "viewfinder.circle",
                          title: "PlantIdentifierCare",
                          message: "Identify plants from a photo + care reminders."),
                    .init(systemImage: "sparkle.magnifyingglass",
                          title: "Go Pro",
                          message: "Unlimited IDs, disease diagnosis, care schedule.")
                ],
                presentsPaywallOnFinish: true,
                accent: .green
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock PlantIdentifierCare Pro",
                subheadline: "Unlimited IDs, disease diagnosis, care schedule.",
                benefits: [
                    .init(systemImage: "infinity", title: "Unlimited IDs"),
                    .init(systemImage: "bolt.fill", title: "Disease diagnosis"),
                    .init(systemImage: "nosign", title: "Care schedule")
                ],
                productIDs: ["plant-id_yearly", "plant-id_weekly"],
                highlightedProductID: "plant-id_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .green, heroSystemImage: "viewfinder.circle")
            )
        )
        return AppFactory(config)
    }
}

@main
struct PlantIdentifierCareApp: App {
    @StateObject private var factory = PlantIdentifierCareFactory.make()

    var body: some Scene {
        WindowGroup {
            ContentView()
                .appFactoryRoot(factory)
                .tint(.green)
        }
    }
}
